# Site settings
title: Kosmetika na Růžové
email: paulikovam@seznam.cz
phone: +420 732 746 265
description: Kosmetika na Růžové > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kosmetikanaruzove.cz" # the base hostname & protocol for your site

facebook_username: Kosmetika na Růžové

# Build settings
markdown: kramdown
